debug: true
endpoints:
    shutdown:
        enabled: true
info:
    id: ${spring.application.name}
logging:
    level:
        com:
            netflix:
                discovery: 'OFF'
                eureka: 'OFF'
        org:
            springframework:
                security: DEBUG
server:
    port: ${PORT:${SERVER_PORT:0}}
spring:
    jpa:
        generate-ddl: true
    rabbitmq:
        host: ${DOCKER_IP}
    redis:
        host: ${DOCKER_IP}
    sleuth:
        log:
            json:
                enabled: true
        sampler:
            percentage: 1.0