quote: "Whatever the question, coffee is almost always the answer."
security:
    user:
        password: starbucks
server:
    port: ${PORT:8443}
    ssl:
        key-store: D:my_private_key.keystore.p12
        key-store-password: starbucks
        keyAlias: my_key_alias
        keyStoreType: PKCS12
spring:
    cloud:
        stream:
            bindings:
                output:
                    destination: test
    rabbitmq:
        host: localhost
    redis:
        host: localhost
        port: 6379
    zipkin:
        base-url: http://localhost:9411
        host: localhost
        port: 9411
zuul:
    routes:
        demo:
            path: /quote/**
            url: forward:/quotorama
        quote-service:
            path: /qs/**
        user:
            path: /user/**
            url: http://localhost:9999/uaa/user
