quote: '"Whatever the question, coffee is almost always the answer."'
server:
    port: ${PORT:8086}
spring:
    cloud:
        stream:
            bindings:
                output:
                    destination: test
    rabbitmq:
        host: localhost
    redis:
        host: localhost
        port: 6379
    zipkin:
        base-url: http://localhost:9411
        host: localhost
        port: 9411
zuul:
    routes:
        demo:
            path: /quote/**
            url: forward:/quotorama
        quote-service:
            path: /qs/**
        user:
            path: /user/**
            url: http://localhost:9999/uaa/user
