security:
    oauth2:
        resource:
            userInfoUri: http://localhost:9999/uaa/user
    sessions: NEVER
server:
    port: ${PORT:8088}
spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: test
                    durableSubscription: true
                    group: test
    rabbitmq:
        host: localhost
    redis:
        host: localhost
        port: 6379
    zipkin:
        base-url: http://localhost:9411
        host: localhost
        port: 9411
